CREATE DATABASE IF NOT EXISTS SeriousMD;

USE SeriousMD;

DROP TABLE Appointments;

CREATE TABLE IF NOT EXISTS Appointments (
    id INT PRIMARY KEY AUTO_INCREMENT,
    time_queued TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    region VARCHAR(8),
    status VARCHAR(9) DEFAULT 'Queued',
    version INT DEFAULT 0
);

